---
- name: Create user   #Name playbook
  hosts: test-hosts   #Group of hosts
  tasks:
    - name: Create user ansible-fleks     #Name for task
      become: true     #Allow to use superuser mode
      user:   #Module
        name: ansible-fleks    #Parametrs
        state: present
