---
- name: "[{{ name }}] : Конфигурация секрета"
  include_tasks: "../secret.yml"
  tags: "sec-conf"

- name: "[{{ name }}] : Выкладка сервиса"
  block:
    - name: "[{{ name }}] : Выкладка сервиса"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ registry_name }}{{ name  }}:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"
  tags: "{{ name }}"