---
- name: Configuration deploy
  hosts: deploy
  become: yes
  gather_facts: yes
  roles:
    - role: preconfig
      tags: preconfig
    - role: deploy
      tags: deploy

- name: Configuration workers
  hosts: worker
  become: yes
  gather_facts: yes
  roles:
    - role: preconfig
      tags: preconfig